export const DATA_OPTIONS_COMPARE = [
  {
    isPreferredBadge: false,
    image: "https://cdn.familyassets.com/wp-content/uploads/2023/10/image2.svg",
    name: "Lakewood Reserve Senior Living",
    address: "1078 S 88th Street, Louisville CO",
    reviewScore: {
      text: "Resident Review Score",
      score: 9.5,
      isInfoCircle: true,
    },
    monthlyPrice: "$5000",
    initialFee: "$500",
    costIcon: "/CostIcon.svg",
    availability: "Available",
    careTypes: [
      "Assisted Living",
      "Independent Living",
      "Skilled Nursing/Rehab",
      "Memory Care",
      "Hospice Care",
    ],
    caregiverToPatientRatio: "1:7",
    careLevels: [
      "24-hour care",
      "Medication management",
      "Housekeeping",
      " Cooking, meal prep, food options",
      "Personal hygiene assistance (dressing, bathing)",
    ],
    amenities: [
      "Adaptive exercise classes",
      "Group activities",
      "Group outings",
      "Safe outdoor space",
      "Pet friendly",
    ],
  },
  {
    isPreferredBadge: true,
    image: "https://cdn.familyassets.com/wp-content/uploads/2023/10/image2.svg",
    name: "Serenity House Assisted Living Hoyt Street",
    address: "1078 S 88th Street, Louisville CO",
    reviewScore: {
      text: "Resident Review Score",
      score: 9.5,
      isInfoCircle: true,
    },
    monthlyPrice: "$5000",
    initialFee: "$500",
    costIcon: "/CostIcon.svg",
    availability: "Available",
    careTypes: ["Assisted Living", "Independent Living", "Memory Care"],
    caregiverToPatientRatio: "1:10",
    careLevels: [
      "24-hour care",
      "Medication management",
      "Housekeeping",
      " Cooking, meal prep, food options",
    ],
    amenities: [
      "Adaptive exercise classes",
      "Group activities",
      "Safe outdoor space",
      "Pet friendly",
    ],
  },
  {
    isPreferredBadge: true,
    image: "https://cdn.familyassets.com/wp-content/uploads/2023/10/image2.svg",
    name: "Brookdale Lakewood",
    address: "1078 S 88th Street, Louisville CO",
    reviewScore: {
      text: "Resident Review Score",
      score: 5.5,
      isInfoCircle: true,
    },
    monthlyPrice: "$5000",
    initialFee: "$500",
    costIcon: "/CostIcon.svg",
    availability: "Waitlist",
    careTypes: ["Assisted Living", "Independent Living"],
    caregiverToPatientRatio: "1:5",
    careLevels: ["24-hour care", "Medication management", "Housekeeping"],
    amenities: [
      "Adaptive exercise classes",
      "Group activities",
      "Pet friendly",
    ],
  },

  {
    isPreferredBadge: true,
    image: "https://cdn.familyassets.com/wp-content/uploads/2023/10/image2.svg",
    name: "Lakeview Senior Living",
    address: "1078 S 88th Street, Louisville CO",
    reviewScore: {
      text: "",
      score: 0,
      isInfoCircle: false,
    },
    monthlyPrice: "$5000",
    initialFee: "$500",
    costIcon: "/CostIcon.svg",
    availability: "Available",
    careTypes: [
      "Assisted Living",
      "Independent Living",
      "Skilled Nursing/Rehab",
      "Memory Care",
    ],
    caregiverToPatientRatio: "1:10",
    careLevels: [
      "Medication management",
      "Housekeeping",
      " Cooking, meal prep, food options",
      "Personal hygiene assistance (dressing, bathing)",
    ],
    amenities: [
      "Adaptive exercise classes",
      "Group activities",
      "Group outings",
      "Safe outdoor space",
    ],
  },
];
